import json
from pathlib import Path

from omegaconf import OmegaConf
import pandas as pd

from nextgen2026_coding_bootcamp.steps.analyze import run_analyze
from nextgen2026_coding_bootcamp.steps.report import run_report


def test_analyze_and_report_generate_expected_baseline_artifacts(tmp_path: Path):
    prepared_csv = tmp_path / "intermediate" / "hourly_bike_data.csv"
    prepared_csv.parent.mkdir(parents=True, exist_ok=True)
    prepared_csv.write_text(
        "date,hour,season,month,weekday,holiday,workingday,day_type,weather,temp_c,feels_like_c,humidity_pct,windspeed_kph,casual,registered,total_rentals\n"
        "2011-01-01,8,winter,1,6,0,0,non_working_day,clear,4.99,3.01,81.0,0.0,3,7,10\n"
        "2011-01-03,8,spring,1,1,0,1,working_day,mist_cloud,5.00,2.00,80.0,6.7,8,12,20\n"
        "2011-01-03,9,spring,1,1,0,1,working_day,mist_cloud,15.00,2.00,80.0,6.7,12,18,30\n"
        "2011-01-03,10,summer,1,1,0,1,working_day,clear,25.00,2.00,80.0,6.7,15,25,40\n"
    )

    cfg = OmegaConf.create(
        {
            "paths": {
                "intermediate_dir": str(tmp_path / "intermediate"),
                "results_dir": str(tmp_path / "results"),
            },
            "analysis": {"high_demand_quantile": 0.9},
            "report": {
                "write_plots": False,
                "write_summary_markdown": True,
            },
        }
    )

    analyze_artifacts = run_analyze(cfg=cfg)
    assert Path(analyze_artifacts["hourly_profile_csv"]).exists()
    assert Path(analyze_artifacts["high_demand_share_csv"]).exists()
    assert Path(analyze_artifacts["weather_summary_csv"]).exists()
    assert Path(analyze_artifacts["summary_json"]).exists()

    hourly_profile = pd.read_csv(analyze_artifacts["hourly_profile_csv"])
    assert {"hour", "day_type", "mean_rentals"}.issubset(set(hourly_profile.columns))
    assert len(hourly_profile) == 4

    high_demand_share = pd.read_csv(analyze_artifacts["high_demand_share_csv"])
    assert list(high_demand_share.columns) == ["hour", "high_demand_share"]
    assert len(high_demand_share) == 3

    weather_summary = pd.read_csv(analyze_artifacts["weather_summary_csv"])
    assert list(weather_summary.columns) == ["weather", "mean_rentals", "observations"]
    assert weather_summary["weather"].tolist() == ["clear", "mist_cloud"]

    summary_payload = json.loads(Path(analyze_artifacts["summary_json"]).read_text())
    assert summary_payload["rows_in"] == 4
    assert summary_payload["rows_high_demand"] == 1

    report_artifacts = run_report(cfg=cfg)
    assert Path(report_artifacts["summary_markdown"]).exists()
    assert report_artifacts["figure_one_png"] is None
    assert report_artifacts["figure_two_png"] is None
    summary_markdown = Path(report_artifacts["summary_markdown"]).read_text()
    assert "# Analysis Summary" in summary_markdown
    assert "Hour with highest high-demand share:" in summary_markdown
    assert "High-demand rows: `1`" in summary_markdown
    assert "Generated by `run_report` from analyze-stage artifacts." in summary_markdown
