from __future__ import annotations

import json
from pathlib import Path
import logging

import pandas as pd

logger = logging.getLogger(__name__)


def _resolve_analyze_inputs(cfg, ctx=None) -> tuple[Path, Path, Path]:
    if ctx is not None:
        analyze_artifact = ctx.artifacts.get("analyze", {})
        if analyze_artifact:
            hourly_profile = analyze_artifact.get("hourly_profile_csv")
            high_demand_share = analyze_artifact.get("high_demand_share_csv")
            summary_json = analyze_artifact.get("summary_json")
            if hourly_profile and high_demand_share and summary_json:
                return Path(hourly_profile), Path(high_demand_share), Path(summary_json)

    base = Path(cfg.paths.results_dir)
    return (
        base / "hourly_profile.csv",
        base / "high_demand_share_by_hour.csv",
        base / "high_demand_summary.json",
    )


def run_report(cfg, ctx=None) -> dict:
    hourly_profile_path, high_demand_share_path, summary_path = _resolve_analyze_inputs(
        cfg=cfg,
        ctx=ctx,
    )

    if ctx is None:
        output_dir = Path(cfg.paths.results_dir)
    else:
        output_dir = ctx.run_dir / "report"
    output_dir.mkdir(parents=True, exist_ok=True)

    logger.info(
        "report:start hourly_profile=%s high_demand_share=%s",
        hourly_profile_path,
        high_demand_share_path,
    )

    hourly_profile = pd.read_csv(hourly_profile_path)
    high_demand_share_by_hour = pd.read_csv(high_demand_share_path)

    figure_one_path = output_dir / "hourly_demand_by_day_type.png"
    figure_two_path = output_dir / "high_demand_share_by_hour.png"
    summary_md_path = output_dir / "analysis_summary.md"

    write_plots = bool(cfg.report.write_plots)
    write_summary_markdown = bool(cfg.report.write_summary_markdown)
    figure_dpi = int(getattr(cfg.report, "figure_dpi", 150))

    if write_plots:
        import matplotlib.pyplot as plt

        fig1, ax1 = plt.subplots(figsize=(10, 5))
        for day_type, group in hourly_profile.groupby("day_type"):
            ax1.plot(group["hour"], group["mean_rentals"], marker="o", label=day_type)
        ax1.set_title("Mean hourly bike rentals by day type")
        ax1.set_xlabel("Hour of day")
        ax1.set_ylabel("Mean rentals")
        ax1.legend()
        ax1.grid(alpha=0.3)
        fig1.tight_layout()
        fig1.savefig(figure_one_path, dpi=figure_dpi)
        plt.close(fig1)

        fig2, ax2 = plt.subplots(figsize=(10, 5))
        ax2.bar(
            high_demand_share_by_hour["hour"],
            high_demand_share_by_hour["high_demand_share"],
        )
        ax2.set_title("Share of high-demand observations by hour")
        ax2.set_xlabel("Hour of day")
        ax2.set_ylabel("High-demand share")
        ax2.grid(axis="y", alpha=0.3)
        fig2.tight_layout()
        fig2.savefig(figure_two_path, dpi=figure_dpi)
        plt.close(fig2)

    summary_payload = None
    if summary_path.exists():
        summary_payload = json.loads(summary_path.read_text())

    if write_summary_markdown:
        top_hour_row = high_demand_share_by_hour.sort_values(
            "high_demand_share",
            ascending=False,
        ).iloc[0]

        lines = ["# Analysis Summary", ""]
        if summary_payload is not None:
            lines.extend(
                [
                    f"- High-demand quantile: `{summary_payload['high_demand_quantile']}`",
                    f"- High-demand threshold: `{summary_payload['high_demand_threshold']:.3f}`",
                    f"- Rows analyzed: `{summary_payload['rows_in']}`",
                    f"- High-demand rows: `{summary_payload['rows_high_demand']}`",
                ]
            )
        lines.extend(
            [
                f"- Hour with highest high-demand share: `{int(top_hour_row['hour'])}`",
                f"- Highest high-demand share value: `{float(top_hour_row['high_demand_share']):.3f}`",
                "",
                "Generated by `run_report` from analyze-stage artifacts.",
            ]
        )
        summary_md_path.write_text("\n".join(lines) + "\n")

    logger.info(
        "report:finish write_plots=%s write_summary_markdown=%s",
        write_plots,
        write_summary_markdown,
    )

    return {
        "hourly_profile_csv": str(hourly_profile_path),
        "high_demand_share_csv": str(high_demand_share_path),
        "summary_json": str(summary_path),
        "figure_one_png": str(figure_one_path) if write_plots else None,
        "figure_two_png": str(figure_two_path) if write_plots else None,
        "summary_markdown": str(summary_md_path) if write_summary_markdown else None,
        "write_plots": write_plots,
        "write_summary_markdown": write_summary_markdown,
    }
